language: java
dist: trusty
branches:
  only:
  - master
before_install: bash etc/ci-setup.sh
install: false
script:
  - /tmp/testrunner/bin/run -c
  - bash etc/hatchet.sh
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  matrix:
  - HEROKU_TEST_STACK="heroku-16"
  - HEROKU_TEST_STACK="heroku-18"
